/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.aqsw.pipe.v1;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Defines the identity of a message using a set of keys extracted from the message payload */
@org.apache.avro.specific.AvroGenerated
public class Classifier extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9113547959292192777L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Classifier\",\"namespace\":\"com.inditex.aqsw.pipe.v1\",\"doc\":\"Defines the identity of a message using a set of keys extracted from the message payload\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"Name of the classifier in order to make comparisons between events with the same classifier defined\"},{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"doc\":\"Ordered values that define the final classifier value\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Classifier> ENCODER =
      new BinaryMessageEncoder<Classifier>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Classifier> DECODER =
      new BinaryMessageDecoder<Classifier>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Classifier> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Classifier> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Classifier>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Classifier to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Classifier from a ByteBuffer. */
  public static Classifier fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of the classifier in order to make comparisons between events with the same classifier defined */
  @Deprecated public java.lang.CharSequence name;
  /** Ordered values that define the final classifier value */
  @Deprecated public java.util.List<java.lang.CharSequence> values;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Classifier() {}

  /**
   * All-args constructor.
   * @param name Name of the classifier in order to make comparisons between events with the same classifier defined
   * @param values Ordered values that define the final classifier value
   */
  public Classifier(java.lang.CharSequence name, java.util.List<java.lang.CharSequence> values) {
    this.name = name;
    this.values = values;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return values;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: values = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return Name of the classifier in order to make comparisons between events with the same classifier defined
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * Name of the classifier in order to make comparisons between events with the same classifier defined
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'values' field.
   * @return Ordered values that define the final classifier value
   */
  public java.util.List<java.lang.CharSequence> getValues() {
    return values;
  }

  /**
   * Sets the value of the 'values' field.
   * Ordered values that define the final classifier value
   * @param value the value to set.
   */
  public void setValues(java.util.List<java.lang.CharSequence> value) {
    this.values = value;
  }

  /**
   * Creates a new Classifier RecordBuilder.
   * @return A new Classifier RecordBuilder
   */
  public static com.inditex.aqsw.pipe.v1.Classifier.Builder newBuilder() {
    return new com.inditex.aqsw.pipe.v1.Classifier.Builder();
  }

  /**
   * Creates a new Classifier RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Classifier RecordBuilder
   */
  public static com.inditex.aqsw.pipe.v1.Classifier.Builder newBuilder(com.inditex.aqsw.pipe.v1.Classifier.Builder other) {
    return new com.inditex.aqsw.pipe.v1.Classifier.Builder(other);
  }

  /**
   * Creates a new Classifier RecordBuilder by copying an existing Classifier instance.
   * @param other The existing instance to copy.
   * @return A new Classifier RecordBuilder
   */
  public static com.inditex.aqsw.pipe.v1.Classifier.Builder newBuilder(com.inditex.aqsw.pipe.v1.Classifier other) {
    return new com.inditex.aqsw.pipe.v1.Classifier.Builder(other);
  }

  /**
   * RecordBuilder for Classifier instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Classifier>
    implements org.apache.avro.data.RecordBuilder<Classifier> {

    /** Name of the classifier in order to make comparisons between events with the same classifier defined */
    private java.lang.CharSequence name;
    /** Ordered values that define the final classifier value */
    private java.util.List<java.lang.CharSequence> values;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.aqsw.pipe.v1.Classifier.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.values)) {
        this.values = data().deepCopy(fields()[1].schema(), other.values);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Classifier instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.aqsw.pipe.v1.Classifier other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.values)) {
        this.values = data().deepCopy(fields()[1].schema(), other.values);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * Name of the classifier in order to make comparisons between events with the same classifier defined
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * Name of the classifier in order to make comparisons between events with the same classifier defined
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.inditex.aqsw.pipe.v1.Classifier.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Name of the classifier in order to make comparisons between events with the same classifier defined
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * Name of the classifier in order to make comparisons between events with the same classifier defined
      * @return This builder.
      */
    public com.inditex.aqsw.pipe.v1.Classifier.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'values' field.
      * Ordered values that define the final classifier value
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getValues() {
      return values;
    }

    /**
      * Sets the value of the 'values' field.
      * Ordered values that define the final classifier value
      * @param value The value of 'values'.
      * @return This builder.
      */
    public com.inditex.aqsw.pipe.v1.Classifier.Builder setValues(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.values = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'values' field has been set.
      * Ordered values that define the final classifier value
      * @return True if the 'values' field has been set, false otherwise.
      */
    public boolean hasValues() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'values' field.
      * Ordered values that define the final classifier value
      * @return This builder.
      */
    public com.inditex.aqsw.pipe.v1.Classifier.Builder clearValues() {
      values = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Classifier build() {
      try {
        Classifier record = new Classifier();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.values = fieldSetFlags()[1] ? this.values : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Classifier>
    WRITER$ = (org.apache.avro.io.DatumWriter<Classifier>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Classifier>
    READER$ = (org.apache.avro.io.DatumReader<Classifier>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
