/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.mecc.mecprsku.api.avro.v2;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Class that holds the list of prices of the sku. */
@org.apache.avro.specific.AvroGenerated
public class OfferSegment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6410202568449769084L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OfferSegment\",\"namespace\":\"com.inditex.mecc.mecprsku.api.avro.v2\",\"doc\":\"Class that holds the list of prices of the sku.\",\"fields\":[{\"name\":\"start_date\",\"type\":\"long\",\"doc\":\"Starting period date in milliseconds since epoch time where the price becomes valid.\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"end_date\",\"type\":\"long\",\"doc\":\"Ending period date in milliseconds since epoch time where the price stops being valid.\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"kind\",\"type\":\"string\",\"doc\":\"Kind of segment: Regular, sales...\"},{\"name\":\"promotion_name\",\"type\":[\"null\",\"string\"],\"doc\":\"Optional name of the promotion associated to the price\",\"default\":null},{\"name\":\"offer_prices\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OfferPrice\",\"doc\":\"Class that holds price information for a given period of time.\",\"fields\":[{\"name\":\"amount\",\"type\":\"long\",\"doc\":\"Current price during the current period expressed in the smallest legal unit available for the price currency (e.g. prices are expressed in euro's cents).\"},{\"name\":\"compare_amount\",\"type\":[\"null\",\"long\"],\"doc\":\"Previous price of the product during a sales period expressed in the smallest legal unit available for the price currency (e.g. prices are expressed in euro's cents). This is optional and used to compare previous and current prices during sales.\"},{\"name\":\"currency_iso\",\"type\":\"string\",\"doc\":\"Currency ISO 4217 code.\"}]}},\"doc\":\"List of prices of the current sku.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OfferSegment> ENCODER =
      new BinaryMessageEncoder<OfferSegment>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OfferSegment> DECODER =
      new BinaryMessageDecoder<OfferSegment>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OfferSegment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OfferSegment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OfferSegment>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OfferSegment to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OfferSegment from a ByteBuffer. */
  public static OfferSegment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Starting period date in milliseconds since epoch time where the price becomes valid. */
  @Deprecated public long start_date;
  /** Ending period date in milliseconds since epoch time where the price stops being valid. */
  @Deprecated public long end_date;
  /** Kind of segment: Regular, sales... */
  @Deprecated public java.lang.CharSequence kind;
  /** Optional name of the promotion associated to the price */
  @Deprecated public java.lang.CharSequence promotion_name;
  /** List of prices of the current sku. */
  @Deprecated public java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice> offer_prices;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OfferSegment() {}

  /**
   * All-args constructor.
   * @param start_date Starting period date in milliseconds since epoch time where the price becomes valid.
   * @param end_date Ending period date in milliseconds since epoch time where the price stops being valid.
   * @param kind Kind of segment: Regular, sales...
   * @param promotion_name Optional name of the promotion associated to the price
   * @param offer_prices List of prices of the current sku.
   */
  public OfferSegment(java.lang.Long start_date, java.lang.Long end_date, java.lang.CharSequence kind, java.lang.CharSequence promotion_name, java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice> offer_prices) {
    this.start_date = start_date;
    this.end_date = end_date;
    this.kind = kind;
    this.promotion_name = promotion_name;
    this.offer_prices = offer_prices;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return start_date;
    case 1: return end_date;
    case 2: return kind;
    case 3: return promotion_name;
    case 4: return offer_prices;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: start_date = (java.lang.Long)value$; break;
    case 1: end_date = (java.lang.Long)value$; break;
    case 2: kind = (java.lang.CharSequence)value$; break;
    case 3: promotion_name = (java.lang.CharSequence)value$; break;
    case 4: offer_prices = (java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'start_date' field.
   * @return Starting period date in milliseconds since epoch time where the price becomes valid.
   */
  public java.lang.Long getStartDate() {
    return start_date;
  }

  /**
   * Sets the value of the 'start_date' field.
   * Starting period date in milliseconds since epoch time where the price becomes valid.
   * @param value the value to set.
   */
  public void setStartDate(java.lang.Long value) {
    this.start_date = value;
  }

  /**
   * Gets the value of the 'end_date' field.
   * @return Ending period date in milliseconds since epoch time where the price stops being valid.
   */
  public java.lang.Long getEndDate() {
    return end_date;
  }

  /**
   * Sets the value of the 'end_date' field.
   * Ending period date in milliseconds since epoch time where the price stops being valid.
   * @param value the value to set.
   */
  public void setEndDate(java.lang.Long value) {
    this.end_date = value;
  }

  /**
   * Gets the value of the 'kind' field.
   * @return Kind of segment: Regular, sales...
   */
  public java.lang.CharSequence getKind() {
    return kind;
  }

  /**
   * Sets the value of the 'kind' field.
   * Kind of segment: Regular, sales...
   * @param value the value to set.
   */
  public void setKind(java.lang.CharSequence value) {
    this.kind = value;
  }

  /**
   * Gets the value of the 'promotion_name' field.
   * @return Optional name of the promotion associated to the price
   */
  public java.lang.CharSequence getPromotionName() {
    return promotion_name;
  }

  /**
   * Sets the value of the 'promotion_name' field.
   * Optional name of the promotion associated to the price
   * @param value the value to set.
   */
  public void setPromotionName(java.lang.CharSequence value) {
    this.promotion_name = value;
  }

  /**
   * Gets the value of the 'offer_prices' field.
   * @return List of prices of the current sku.
   */
  public java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice> getOfferPrices() {
    return offer_prices;
  }

  /**
   * Sets the value of the 'offer_prices' field.
   * List of prices of the current sku.
   * @param value the value to set.
   */
  public void setOfferPrices(java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice> value) {
    this.offer_prices = value;
  }

  /**
   * Creates a new OfferSegment RecordBuilder.
   * @return A new OfferSegment RecordBuilder
   */
  public static com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder newBuilder() {
    return new com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder();
  }

  /**
   * Creates a new OfferSegment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OfferSegment RecordBuilder
   */
  public static com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder newBuilder(com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder other) {
    return new com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder(other);
  }

  /**
   * Creates a new OfferSegment RecordBuilder by copying an existing OfferSegment instance.
   * @param other The existing instance to copy.
   * @return A new OfferSegment RecordBuilder
   */
  public static com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder newBuilder(com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment other) {
    return new com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder(other);
  }

  /**
   * RecordBuilder for OfferSegment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OfferSegment>
    implements org.apache.avro.data.RecordBuilder<OfferSegment> {

    /** Starting period date in milliseconds since epoch time where the price becomes valid. */
    private long start_date;
    /** Ending period date in milliseconds since epoch time where the price stops being valid. */
    private long end_date;
    /** Kind of segment: Regular, sales... */
    private java.lang.CharSequence kind;
    /** Optional name of the promotion associated to the price */
    private java.lang.CharSequence promotion_name;
    /** List of prices of the current sku. */
    private java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice> offer_prices;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.start_date)) {
        this.start_date = data().deepCopy(fields()[0].schema(), other.start_date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.end_date)) {
        this.end_date = data().deepCopy(fields()[1].schema(), other.end_date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.kind)) {
        this.kind = data().deepCopy(fields()[2].schema(), other.kind);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.promotion_name)) {
        this.promotion_name = data().deepCopy(fields()[3].schema(), other.promotion_name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.offer_prices)) {
        this.offer_prices = data().deepCopy(fields()[4].schema(), other.offer_prices);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OfferSegment instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.start_date)) {
        this.start_date = data().deepCopy(fields()[0].schema(), other.start_date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.end_date)) {
        this.end_date = data().deepCopy(fields()[1].schema(), other.end_date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.kind)) {
        this.kind = data().deepCopy(fields()[2].schema(), other.kind);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.promotion_name)) {
        this.promotion_name = data().deepCopy(fields()[3].schema(), other.promotion_name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.offer_prices)) {
        this.offer_prices = data().deepCopy(fields()[4].schema(), other.offer_prices);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'start_date' field.
      * Starting period date in milliseconds since epoch time where the price becomes valid.
      * @return The value.
      */
    public java.lang.Long getStartDate() {
      return start_date;
    }

    /**
      * Sets the value of the 'start_date' field.
      * Starting period date in milliseconds since epoch time where the price becomes valid.
      * @param value The value of 'start_date'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder setStartDate(long value) {
      validate(fields()[0], value);
      this.start_date = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'start_date' field has been set.
      * Starting period date in milliseconds since epoch time where the price becomes valid.
      * @return True if the 'start_date' field has been set, false otherwise.
      */
    public boolean hasStartDate() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'start_date' field.
      * Starting period date in milliseconds since epoch time where the price becomes valid.
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder clearStartDate() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'end_date' field.
      * Ending period date in milliseconds since epoch time where the price stops being valid.
      * @return The value.
      */
    public java.lang.Long getEndDate() {
      return end_date;
    }

    /**
      * Sets the value of the 'end_date' field.
      * Ending period date in milliseconds since epoch time where the price stops being valid.
      * @param value The value of 'end_date'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder setEndDate(long value) {
      validate(fields()[1], value);
      this.end_date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'end_date' field has been set.
      * Ending period date in milliseconds since epoch time where the price stops being valid.
      * @return True if the 'end_date' field has been set, false otherwise.
      */
    public boolean hasEndDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'end_date' field.
      * Ending period date in milliseconds since epoch time where the price stops being valid.
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder clearEndDate() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'kind' field.
      * Kind of segment: Regular, sales...
      * @return The value.
      */
    public java.lang.CharSequence getKind() {
      return kind;
    }

    /**
      * Sets the value of the 'kind' field.
      * Kind of segment: Regular, sales...
      * @param value The value of 'kind'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder setKind(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.kind = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'kind' field has been set.
      * Kind of segment: Regular, sales...
      * @return True if the 'kind' field has been set, false otherwise.
      */
    public boolean hasKind() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'kind' field.
      * Kind of segment: Regular, sales...
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder clearKind() {
      kind = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'promotion_name' field.
      * Optional name of the promotion associated to the price
      * @return The value.
      */
    public java.lang.CharSequence getPromotionName() {
      return promotion_name;
    }

    /**
      * Sets the value of the 'promotion_name' field.
      * Optional name of the promotion associated to the price
      * @param value The value of 'promotion_name'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder setPromotionName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.promotion_name = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'promotion_name' field has been set.
      * Optional name of the promotion associated to the price
      * @return True if the 'promotion_name' field has been set, false otherwise.
      */
    public boolean hasPromotionName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'promotion_name' field.
      * Optional name of the promotion associated to the price
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder clearPromotionName() {
      promotion_name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'offer_prices' field.
      * List of prices of the current sku.
      * @return The value.
      */
    public java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice> getOfferPrices() {
      return offer_prices;
    }

    /**
      * Sets the value of the 'offer_prices' field.
      * List of prices of the current sku.
      * @param value The value of 'offer_prices'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder setOfferPrices(java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice> value) {
      validate(fields()[4], value);
      this.offer_prices = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'offer_prices' field has been set.
      * List of prices of the current sku.
      * @return True if the 'offer_prices' field has been set, false otherwise.
      */
    public boolean hasOfferPrices() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'offer_prices' field.
      * List of prices of the current sku.
      * @return This builder.
      */
    public com.inditex.mecc.mecprsku.api.avro.v2.OfferSegment.Builder clearOfferPrices() {
      offer_prices = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OfferSegment build() {
      try {
        OfferSegment record = new OfferSegment();
        record.start_date = fieldSetFlags()[0] ? this.start_date : (java.lang.Long) defaultValue(fields()[0]);
        record.end_date = fieldSetFlags()[1] ? this.end_date : (java.lang.Long) defaultValue(fields()[1]);
        record.kind = fieldSetFlags()[2] ? this.kind : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.promotion_name = fieldSetFlags()[3] ? this.promotion_name : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.offer_prices = fieldSetFlags()[4] ? this.offer_prices : (java.util.List<com.inditex.mecc.mecprsku.api.avro.v2.OfferPrice>) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OfferSegment>
    WRITER$ = (org.apache.avro.io.DatumWriter<OfferSegment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OfferSegment>
    READER$ = (org.apache.avro.io.DatumReader<OfferSegment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
