/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.mecc.ecomloadbk.api.avro.v1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Class that holds the attribute information of a base product */
@org.apache.avro.specific.AvroGenerated
public class BaseProductCustomAttributeType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5687960214822954389L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BaseProductCustomAttributeType\",\"namespace\":\"com.inditex.mecc.ecomloadbk.api.avro.v1\",\"doc\":\"Class that holds the attribute information of a base product\",\"fields\":[{\"name\":\"attr_code\",\"type\":\"string\",\"doc\":\"Key of the attribute\"},{\"name\":\"attr_type\",\"type\":{\"type\":\"enum\",\"name\":\"AttrTypeEnum\",\"symbols\":[\"NUMBER\",\"STRING\",\"BOOLEAN\"]},\"doc\":\"Primitive data type of the attribute\"},{\"name\":\"attr_value\",\"type\":\"string\",\"doc\":\"Value of the attribute\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BaseProductCustomAttributeType> ENCODER =
      new BinaryMessageEncoder<BaseProductCustomAttributeType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BaseProductCustomAttributeType> DECODER =
      new BinaryMessageDecoder<BaseProductCustomAttributeType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BaseProductCustomAttributeType> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BaseProductCustomAttributeType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BaseProductCustomAttributeType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BaseProductCustomAttributeType>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BaseProductCustomAttributeType to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BaseProductCustomAttributeType from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BaseProductCustomAttributeType instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BaseProductCustomAttributeType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Key of the attribute */
  @Deprecated public java.lang.CharSequence attr_code;
  /** Primitive data type of the attribute */
  @Deprecated public com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum attr_type;
  /** Value of the attribute */
  @Deprecated public java.lang.CharSequence attr_value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BaseProductCustomAttributeType() {}

  /**
   * All-args constructor.
   * @param attr_code Key of the attribute
   * @param attr_type Primitive data type of the attribute
   * @param attr_value Value of the attribute
   */
  public BaseProductCustomAttributeType(java.lang.CharSequence attr_code, com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum attr_type, java.lang.CharSequence attr_value) {
    this.attr_code = attr_code;
    this.attr_type = attr_type;
    this.attr_value = attr_value;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return attr_code;
    case 1: return attr_type;
    case 2: return attr_value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: attr_code = (java.lang.CharSequence)value$; break;
    case 1: attr_type = (com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum)value$; break;
    case 2: attr_value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'attr_code' field.
   * @return Key of the attribute
   */
  public java.lang.CharSequence getAttrCode() {
    return attr_code;
  }


  /**
   * Sets the value of the 'attr_code' field.
   * Key of the attribute
   * @param value the value to set.
   */
  public void setAttrCode(java.lang.CharSequence value) {
    this.attr_code = value;
  }

  /**
   * Gets the value of the 'attr_type' field.
   * @return Primitive data type of the attribute
   */
  public com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum getAttrType() {
    return attr_type;
  }


  /**
   * Sets the value of the 'attr_type' field.
   * Primitive data type of the attribute
   * @param value the value to set.
   */
  public void setAttrType(com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum value) {
    this.attr_type = value;
  }

  /**
   * Gets the value of the 'attr_value' field.
   * @return Value of the attribute
   */
  public java.lang.CharSequence getAttrValue() {
    return attr_value;
  }


  /**
   * Sets the value of the 'attr_value' field.
   * Value of the attribute
   * @param value the value to set.
   */
  public void setAttrValue(java.lang.CharSequence value) {
    this.attr_value = value;
  }

  /**
   * Creates a new BaseProductCustomAttributeType RecordBuilder.
   * @return A new BaseProductCustomAttributeType RecordBuilder
   */
  public static com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder newBuilder() {
    return new com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder();
  }

  /**
   * Creates a new BaseProductCustomAttributeType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BaseProductCustomAttributeType RecordBuilder
   */
  public static com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder newBuilder(com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder other) {
    if (other == null) {
      return new com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder();
    } else {
      return new com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder(other);
    }
  }

  /**
   * Creates a new BaseProductCustomAttributeType RecordBuilder by copying an existing BaseProductCustomAttributeType instance.
   * @param other The existing instance to copy.
   * @return A new BaseProductCustomAttributeType RecordBuilder
   */
  public static com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder newBuilder(com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType other) {
    if (other == null) {
      return new com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder();
    } else {
      return new com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder(other);
    }
  }

  /**
   * RecordBuilder for BaseProductCustomAttributeType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BaseProductCustomAttributeType>
    implements org.apache.avro.data.RecordBuilder<BaseProductCustomAttributeType> {

    /** Key of the attribute */
    private java.lang.CharSequence attr_code;
    /** Primitive data type of the attribute */
    private com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum attr_type;
    /** Value of the attribute */
    private java.lang.CharSequence attr_value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.attr_code)) {
        this.attr_code = data().deepCopy(fields()[0].schema(), other.attr_code);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.attr_type)) {
        this.attr_type = data().deepCopy(fields()[1].schema(), other.attr_type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.attr_value)) {
        this.attr_value = data().deepCopy(fields()[2].schema(), other.attr_value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing BaseProductCustomAttributeType instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.attr_code)) {
        this.attr_code = data().deepCopy(fields()[0].schema(), other.attr_code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.attr_type)) {
        this.attr_type = data().deepCopy(fields()[1].schema(), other.attr_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.attr_value)) {
        this.attr_value = data().deepCopy(fields()[2].schema(), other.attr_value);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'attr_code' field.
      * Key of the attribute
      * @return The value.
      */
    public java.lang.CharSequence getAttrCode() {
      return attr_code;
    }


    /**
      * Sets the value of the 'attr_code' field.
      * Key of the attribute
      * @param value The value of 'attr_code'.
      * @return This builder.
      */
    public com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder setAttrCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.attr_code = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'attr_code' field has been set.
      * Key of the attribute
      * @return True if the 'attr_code' field has been set, false otherwise.
      */
    public boolean hasAttrCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'attr_code' field.
      * Key of the attribute
      * @return This builder.
      */
    public com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder clearAttrCode() {
      attr_code = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'attr_type' field.
      * Primitive data type of the attribute
      * @return The value.
      */
    public com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum getAttrType() {
      return attr_type;
    }


    /**
      * Sets the value of the 'attr_type' field.
      * Primitive data type of the attribute
      * @param value The value of 'attr_type'.
      * @return This builder.
      */
    public com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder setAttrType(com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum value) {
      validate(fields()[1], value);
      this.attr_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'attr_type' field has been set.
      * Primitive data type of the attribute
      * @return True if the 'attr_type' field has been set, false otherwise.
      */
    public boolean hasAttrType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'attr_type' field.
      * Primitive data type of the attribute
      * @return This builder.
      */
    public com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder clearAttrType() {
      attr_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'attr_value' field.
      * Value of the attribute
      * @return The value.
      */
    public java.lang.CharSequence getAttrValue() {
      return attr_value;
    }


    /**
      * Sets the value of the 'attr_value' field.
      * Value of the attribute
      * @param value The value of 'attr_value'.
      * @return This builder.
      */
    public com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder setAttrValue(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.attr_value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'attr_value' field has been set.
      * Value of the attribute
      * @return True if the 'attr_value' field has been set, false otherwise.
      */
    public boolean hasAttrValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'attr_value' field.
      * Value of the attribute
      * @return This builder.
      */
    public com.inditex.mecc.ecomloadbk.api.avro.v1.BaseProductCustomAttributeType.Builder clearAttrValue() {
      attr_value = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BaseProductCustomAttributeType build() {
      try {
        BaseProductCustomAttributeType record = new BaseProductCustomAttributeType();
        record.attr_code = fieldSetFlags()[0] ? this.attr_code : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.attr_type = fieldSetFlags()[1] ? this.attr_type : (com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum) defaultValue(fields()[1]);
        record.attr_value = fieldSetFlags()[2] ? this.attr_value : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BaseProductCustomAttributeType>
    WRITER$ = (org.apache.avro.io.DatumWriter<BaseProductCustomAttributeType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BaseProductCustomAttributeType>
    READER$ = (org.apache.avro.io.DatumReader<BaseProductCustomAttributeType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.attr_code);

    out.writeEnum(this.attr_type.ordinal());

    out.writeString(this.attr_value);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.attr_code = in.readString(this.attr_code instanceof Utf8 ? (Utf8)this.attr_code : null);

      this.attr_type = com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum.values()[in.readEnum()];

      this.attr_value = in.readString(this.attr_value instanceof Utf8 ? (Utf8)this.attr_value : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.attr_code = in.readString(this.attr_code instanceof Utf8 ? (Utf8)this.attr_code : null);
          break;

        case 1:
          this.attr_type = com.inditex.mecc.ecomloadbk.api.avro.v1.AttrTypeEnum.values()[in.readEnum()];
          break;

        case 2:
          this.attr_value = in.readString(this.attr_value instanceof Utf8 ? (Utf8)this.attr_value : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










