/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.mecc.ecomloadbk.api.avro.v1;
@org.apache.avro.specific.AvroGenerated
public enum KindTypeEnum implements org.apache.avro.generic.GenericEnumSymbol<KindTypeEnum> {
  REGULAR, SALES, EVENT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"KindTypeEnum\",\"namespace\":\"com.inditex.mecc.ecomloadbk.api.avro.v1\",\"symbols\":[\"REGULAR\",\"SALES\",\"EVENT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
