/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.mecc.mecprwat.api.avro.v2;
@org.apache.avro.specific.AvroGenerated
public enum AvailabilitySubscriptionType implements org.apache.avro.generic.GenericEnumSymbol<AvailabilitySubscriptionType> {
  BACK_SOON, COMING_SOON  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvailabilitySubscriptionType\",\"namespace\":\"com.inditex.mecc.mecprwat.api.avro.v2\",\"symbols\":[\"BACK_SOON\",\"COMING_SOON\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
