/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.mecc.mecprwat.api.avro.v2;
@org.apache.avro.specific.AvroGenerated
public enum CommercialComponentType implements org.apache.avro.generic.GenericEnumSymbol<CommercialComponentType> {
  PRODUCT, SINGLE_COMPONENT, BUNDLE_COMPONENT, BANNER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CommercialComponentType\",\"namespace\":\"com.inditex.mecc.mecprwat.api.avro.v2\",\"symbols\":[\"PRODUCT\",\"SINGLE_COMPONENT\",\"BUNDLE_COMPONENT\",\"BANNER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
