/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.mecc.mecprwat.api.avro.v2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Class that holds info about a perfume. */
@org.apache.avro.specific.AvroGenerated
public class ProductVolume extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3348169177333548808L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductVolume\",\"namespace\":\"com.inditex.mecc.mecprwat.api.avro.v2\",\"doc\":\"Class that holds info about a perfume.\",\"fields\":[{\"name\":\"number\",\"type\":\"int\",\"doc\":\"Cardinality of the volume (relative to the next unit).\"},{\"name\":\"unit\",\"type\":\"string\",\"doc\":\"Unit of measurement. i.e ml.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductVolume> ENCODER =
      new BinaryMessageEncoder<ProductVolume>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductVolume> DECODER =
      new BinaryMessageDecoder<ProductVolume>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductVolume> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductVolume> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductVolume> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProductVolume>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductVolume to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductVolume from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductVolume instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductVolume fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Cardinality of the volume (relative to the next unit). */
  @Deprecated public int number;
  /** Unit of measurement. i.e ml. */
  @Deprecated public java.lang.CharSequence unit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductVolume() {}

  /**
   * All-args constructor.
   * @param number Cardinality of the volume (relative to the next unit).
   * @param unit Unit of measurement. i.e ml.
   */
  public ProductVolume(java.lang.Integer number, java.lang.CharSequence unit) {
    this.number = number;
    this.unit = unit;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return number;
    case 1: return unit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: number = (java.lang.Integer)value$; break;
    case 1: unit = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'number' field.
   * @return Cardinality of the volume (relative to the next unit).
   */
  public int getNumber() {
    return number;
  }


  /**
   * Sets the value of the 'number' field.
   * Cardinality of the volume (relative to the next unit).
   * @param value the value to set.
   */
  public void setNumber(int value) {
    this.number = value;
  }

  /**
   * Gets the value of the 'unit' field.
   * @return Unit of measurement. i.e ml.
   */
  public java.lang.CharSequence getUnit() {
    return unit;
  }


  /**
   * Sets the value of the 'unit' field.
   * Unit of measurement. i.e ml.
   * @param value the value to set.
   */
  public void setUnit(java.lang.CharSequence value) {
    this.unit = value;
  }

  /**
   * Creates a new ProductVolume RecordBuilder.
   * @return A new ProductVolume RecordBuilder
   */
  public static com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder newBuilder() {
    return new com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder();
  }

  /**
   * Creates a new ProductVolume RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductVolume RecordBuilder
   */
  public static com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder newBuilder(com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder other) {
    if (other == null) {
      return new com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder();
    } else {
      return new com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder(other);
    }
  }

  /**
   * Creates a new ProductVolume RecordBuilder by copying an existing ProductVolume instance.
   * @param other The existing instance to copy.
   * @return A new ProductVolume RecordBuilder
   */
  public static com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder newBuilder(com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume other) {
    if (other == null) {
      return new com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder();
    } else {
      return new com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductVolume instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductVolume>
    implements org.apache.avro.data.RecordBuilder<ProductVolume> {

    /** Cardinality of the volume (relative to the next unit). */
    private int number;
    /** Unit of measurement. i.e ml. */
    private java.lang.CharSequence unit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.number)) {
        this.number = data().deepCopy(fields()[0].schema(), other.number);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.unit)) {
        this.unit = data().deepCopy(fields()[1].schema(), other.unit);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductVolume instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.number)) {
        this.number = data().deepCopy(fields()[0].schema(), other.number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.unit)) {
        this.unit = data().deepCopy(fields()[1].schema(), other.unit);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'number' field.
      * Cardinality of the volume (relative to the next unit).
      * @return The value.
      */
    public int getNumber() {
      return number;
    }


    /**
      * Sets the value of the 'number' field.
      * Cardinality of the volume (relative to the next unit).
      * @param value The value of 'number'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder setNumber(int value) {
      validate(fields()[0], value);
      this.number = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'number' field has been set.
      * Cardinality of the volume (relative to the next unit).
      * @return True if the 'number' field has been set, false otherwise.
      */
    public boolean hasNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'number' field.
      * Cardinality of the volume (relative to the next unit).
      * @return This builder.
      */
    public com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder clearNumber() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'unit' field.
      * Unit of measurement. i.e ml.
      * @return The value.
      */
    public java.lang.CharSequence getUnit() {
      return unit;
    }


    /**
      * Sets the value of the 'unit' field.
      * Unit of measurement. i.e ml.
      * @param value The value of 'unit'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder setUnit(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.unit = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'unit' field has been set.
      * Unit of measurement. i.e ml.
      * @return True if the 'unit' field has been set, false otherwise.
      */
    public boolean hasUnit() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'unit' field.
      * Unit of measurement. i.e ml.
      * @return This builder.
      */
    public com.inditex.mecc.mecprwat.api.avro.v2.ProductVolume.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductVolume build() {
      try {
        ProductVolume record = new ProductVolume();
        record.number = fieldSetFlags()[0] ? this.number : (java.lang.Integer) defaultValue(fields()[0]);
        record.unit = fieldSetFlags()[1] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductVolume>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductVolume>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductVolume>
    READER$ = (org.apache.avro.io.DatumReader<ProductVolume>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.number);

    out.writeString(this.unit);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.number = in.readInt();

      this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.number = in.readInt();
          break;

        case 1:
          this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










