/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inditex.mecc.mecprwat.api.avro.v2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Class that holds SEO information. */
@org.apache.avro.specific.AvroGenerated
public class SeoInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4547120230980052460L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SeoInfo\",\"namespace\":\"com.inditex.mecc.mecprwat.api.avro.v2\",\"doc\":\"Class that holds SEO information.\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"SEO identifier.\"},{\"name\":\"keywords\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"I18NText\",\"doc\":\"Class that holds a text and its locale ISO code.\",\"fields\":[{\"name\":\"iso_code\",\"type\":\"string\",\"doc\":\"Locale ISO code.\"},{\"name\":\"text\",\"type\":\"string\",\"doc\":\"Internationalized text.\"}]}},\"doc\":\"Optional list of internationalized SEO keywords.\",\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SeoInfo> ENCODER =
      new BinaryMessageEncoder<SeoInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SeoInfo> DECODER =
      new BinaryMessageDecoder<SeoInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SeoInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SeoInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SeoInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SeoInfo>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SeoInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SeoInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SeoInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SeoInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** SEO identifier. */
  @Deprecated public java.lang.CharSequence id;
  /** Optional list of internationalized SEO keywords. */
  @Deprecated public java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> keywords;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SeoInfo() {}

  /**
   * All-args constructor.
   * @param id SEO identifier.
   * @param keywords Optional list of internationalized SEO keywords.
   */
  public SeoInfo(java.lang.CharSequence id, java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> keywords) {
    this.id = id;
    this.keywords = keywords;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return keywords;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: keywords = (java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return SEO identifier.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * SEO identifier.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'keywords' field.
   * @return Optional list of internationalized SEO keywords.
   */
  public java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> getKeywords() {
    return keywords;
  }


  /**
   * Sets the value of the 'keywords' field.
   * Optional list of internationalized SEO keywords.
   * @param value the value to set.
   */
  public void setKeywords(java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> value) {
    this.keywords = value;
  }

  /**
   * Creates a new SeoInfo RecordBuilder.
   * @return A new SeoInfo RecordBuilder
   */
  public static com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder newBuilder() {
    return new com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder();
  }

  /**
   * Creates a new SeoInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SeoInfo RecordBuilder
   */
  public static com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder newBuilder(com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder other) {
    if (other == null) {
      return new com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder();
    } else {
      return new com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder(other);
    }
  }

  /**
   * Creates a new SeoInfo RecordBuilder by copying an existing SeoInfo instance.
   * @param other The existing instance to copy.
   * @return A new SeoInfo RecordBuilder
   */
  public static com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder newBuilder(com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo other) {
    if (other == null) {
      return new com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder();
    } else {
      return new com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for SeoInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SeoInfo>
    implements org.apache.avro.data.RecordBuilder<SeoInfo> {

    /** SEO identifier. */
    private java.lang.CharSequence id;
    /** Optional list of internationalized SEO keywords. */
    private java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> keywords;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.keywords)) {
        this.keywords = data().deepCopy(fields()[1].schema(), other.keywords);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing SeoInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.keywords)) {
        this.keywords = data().deepCopy(fields()[1].schema(), other.keywords);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * SEO identifier.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * SEO identifier.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * SEO identifier.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * SEO identifier.
      * @return This builder.
      */
    public com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'keywords' field.
      * Optional list of internationalized SEO keywords.
      * @return The value.
      */
    public java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> getKeywords() {
      return keywords;
    }


    /**
      * Sets the value of the 'keywords' field.
      * Optional list of internationalized SEO keywords.
      * @param value The value of 'keywords'.
      * @return This builder.
      */
    public com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder setKeywords(java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> value) {
      validate(fields()[1], value);
      this.keywords = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'keywords' field has been set.
      * Optional list of internationalized SEO keywords.
      * @return True if the 'keywords' field has been set, false otherwise.
      */
    public boolean hasKeywords() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'keywords' field.
      * Optional list of internationalized SEO keywords.
      * @return This builder.
      */
    public com.inditex.mecc.mecprwat.api.avro.v2.SeoInfo.Builder clearKeywords() {
      keywords = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SeoInfo build() {
      try {
        SeoInfo record = new SeoInfo();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.keywords = fieldSetFlags()[1] ? this.keywords : (java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SeoInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<SeoInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SeoInfo>
    READER$ = (org.apache.avro.io.DatumReader<SeoInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    long size0 = this.keywords.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.inditex.mecc.mecprwat.api.avro.v2.I18NText e0: this.keywords) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      long size0 = in.readArrayStart();
      java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> a0 = this.keywords;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.inditex.mecc.mecprwat.api.avro.v2.I18NText>((int)size0, SCHEMA$.getField("keywords").schema());
        this.keywords = a0;
      } else a0.clear();
      SpecificData.Array<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.inditex.mecc.mecprwat.api.avro.v2.I18NText>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.inditex.mecc.mecprwat.api.avro.v2.I18NText e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.inditex.mecc.mecprwat.api.avro.v2.I18NText();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> a0 = this.keywords;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.inditex.mecc.mecprwat.api.avro.v2.I18NText>((int)size0, SCHEMA$.getField("keywords").schema());
            this.keywords = a0;
          } else a0.clear();
          SpecificData.Array<com.inditex.mecc.mecprwat.api.avro.v2.I18NText> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.inditex.mecc.mecprwat.api.avro.v2.I18NText>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.inditex.mecc.mecprwat.api.avro.v2.I18NText e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.inditex.mecc.mecprwat.api.avro.v2.I18NText();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










